# @format
---
env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
rules:
  no-unused-vars: warn
  prettier/prettier:
    - error
    - endOfLine: auto
      jsxSingleQuote: true
  react/react-in-jsx-scope: 'off'
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.js'
        - '.jsx'
  react/jsx-props-no-spreading:
    - 1
    - custom: ignore
  react/no-unused-prop-types: warn
  react/require-default-props: 'off'
  import/prefer-default-export: 'off'
  import/no-cycle: 'off'
  react/jsx-curly-spacing:
    - 2
    - never
  react/function-component-definition: 'off'
settings:
  import/resolver:
    node:
      paths:
        - src
