# @format
---
env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:react/jsx-runtime
  - plugin:prettier/recommended
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - prettier
rules:
  consistent-return: 'off'
  import/prefer-default-export: 'off'
  react/function-component-definition: 'off'
  react/jsx-props-no-spreading: 'off'
  #   - custom: ignore
  react/require-default-props: 'off'
  no-unused-vars: warn
  prettier/prettier:
    - warn
#   - endOfLine: auto
#     jsxSingleQuote: true
# react/react-in-jsx-scope: 'off'
# react/jsx-filename-extension:
#   - 1
#   - extensions:
#       - '.js'
#       - '.jsx'
# react/no-unused-prop-types: warn
# import/no-cycle: 'off'
settings:
  import/resolver:
    node:
      paths:
        - 'src'
